module.exports = {
    client_url: process.env.CLIENT_URL,
    jwt_key: process.env.JWT_SECRET_KEY,
    salt_rounds: process.env.SALT_ROUNDS,
    admin_psw: process.env.ADMIN_PASSWORD,
    api_key: process.env.CLOUDINARY_API_KEY,
    db_connection: process.env.DB_CONNECTION,
    node_env: process.env.NODE_ENVIRONMENT,
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_secret: process.env.CLOUDINARY_API_SECRET,
    def_psw: process.env.def_psw,
    project_key_id: process.env.PROJECT_KEY_ID,
    project_key: process.env.PROJECT_KEY.replace(/\\n/g, '\n'),
    client_email: process.env.PROJECT_CLIENT_EMAIL,
    client_id: process.env.PROJECT_CLIENT_ID,
    auth_uri: process.env.PROJECT_AUTH_URI,
    token_uri: process.env.PROJECT_TOKEN_URI,
    auth_cert_url: process.env.PROJECT_AUTH_CERT_URL,
    client_cert_url: process.env.PROJECT_CLIENT_CERT_URL,
    
};